#log4j.appender.stdout=org.apache.log4j.ConsoleAppender
#log4j.appender.stdout.target=System.out
#log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
#log4j.appender.stdout.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss} %10p (%c:%M) - %m%n
#log4j.rootLogger=INFO, stdout
##log4j.rootLogger=ERROR,stdout
##log4j.rootLogger=WARN,stdout
##log4j.rootLogger=stdout


status = warn
name = PropertiesConfig

appender.console.type = Console
appender.console.name = STDOUT
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n

rootLogger.level = info
rootLogger.appenderRefs = stdout
rootLogger.appenderRef.stdout.ref = STDOUT
# ??? log4j2.properties
logger.sqlserver.name = com.ververica.cdc.connectors.sqlserver
logger.sqlserver.level = DEBUG